blog/urls.py
from django.conf.urls import url, include
from django.urls import path
from blog import views
from rest_framework import routers

app_name = 'blog'

# 定义restful的路由地址
router = routers.DefaultRouter()

# 注册restful的路由地址
router.register(r'getarticleinfo', views.GetArticleInfo)
router.register(r'posts', views.PostViewSet, basename='post')
router.register(r"search", views.PostSearchView, basename="search")

urlpatterns = [
    url('^$', views.index, name='index'),
    url(r'^api/', include(router.urls)),
    path('api/index/', views.IndexPostListAPIView.as_view()),
    # path('api/single/', views.PostViewSet.as_view({'get': 'retrieve'})),
    path('api/auth/', include("rest_framework.urls", namespace="rest_framework")),
    url(r'^search/', views.MySearchView(), name='haystack_search'),
    url(r'^index/$', views.blog_index),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/$', views.blog_info, name='article'),
    url(r'^list/$', views.blog_list),
    url(r'^article/(?P<article_id>[0-9]+)/comment/(?P<cid>.+)', views.comment_view, name='comment'),
    url(r'^contact-us/$', views.contact),
    url(r'^savemessage/$', views.savemessage),
    url(r'^articles/(.+)/$', views.blog_category),
    url(r'^greats/$', views.greats),
    url(r'^admin/$', views.admininndex),
    url(r'^admincharts/$', views.admincharts),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.LogoutView.as_view()),
    url(r'^register/$', views.register_view),
    url(r'^upload_file/$', views.upload_file),
    url(r'^file/$', views.Jiafile),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/editor/$', views.usereditor),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/editor/save/$', views.article_save),
    url(r'^mylist/$', views.mylist),
    url(r'^mylist/(?P<article_status>.+)/$', views.mylist_para),
    url(r'^article/editor/create/$', views.article_create),
    url(r'^article/editor/create/save/$', views.article_create_save),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/editor/delete/', views.article_delete),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/cancelcollect/', views.cancelcollect),
    url(r'^editor/userbrief/$', views.editor_userbrief),
    url(r'^editor/addcategory/$', views.editor_addcategory),
    url(r'^onlineeditor/$', views.pyeditor),
    url(r'^api/$', views.api),
    url(r'^upload_images/(?P<article_id>[0-9]+)/$', views.upload_images),
    url(r'^recruitment/$', views.recruitment),
    url(r'^recruitment/info/$', views.recruitment_info),
    url(r'^recruitment/findme/$', views.findme),
    url(r'^film/', views.movie_list, name="movie"),
    url(r'^deletefile/$', views.deletefile),
    url(r'^ajfileupload/$', views.ajupload_file),
    url(r'^filecheck/$', views.filecheck),
    url(r'^list/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.blog_time),
    url(r'^jiadmin/', views.JiaAdmin.as_view()),
    url(r'^resume/', views.Resume.as_view()),
    url(r'^collect/$', views.collect),
    url(r'^comments/(?P<article_id>[0-9]+)$', views.comments),
    url(r'^rss/$', views.RssFeed(), name='rss'),
    url(r'^searchfile/$', views.search_file),
    url(r'^getallarticle/$', views.get_article_all),
    url(r'^getsinglearticle/(?P<article_id>[0-9]+)/$', views.get_article_single),
    url(r'^single-article/(?P<rand_id>[A-Za-z0-9]+)/$', views.single_article),
    url(r'^getallcategory/$', views.get_categroy_all),
    url(r'^getcategoryarticles/(.+)/$', views.get_article_category),
    url(r'^gettagarticles/(.+)/$', views.get_article_tag),
    url(r'^new/search/$', views.BlogSearch.as_view()),
    url(r'^archive/$', views.BlogPostArchive.as_view()),
    url(r'^new/index/$', views.Index.as_view()),
    url(r'^post/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/$', views.BlogPost.as_view()),
    url(r'^upload_file_springboot/$', views.upload_facepic_springboot),
    url(r'^sign_in/$', views.sign_in),
    url(r'^getlovefzytodo/$', views.GetLoveFZYToDoList.as_view()),
    url(r'^getlovefzydown/$', views.GetLoveFZYDownList.as_view()),
    url(r'^postlovefzy/$', views.PostLoveFZYInfo.as_view()),
    url(r'^getlovefzytimeline/$', views.GetLoveFZYTimeline.as_view()),
    url(r'^tags/$', views.show_tags),
    url(r'^api/upload/resumes/$', views.upload_resumes),
    url(r'^api/edit/article/(?P<rand_id>[A-Za-z0-9]+)/$', views.edit_article),
    # url(r'^convert/$', views.convert),
]

blogproject/urls.py
from django.conf.urls import url
from blogproject import views
from blogproject.views import PostArchiveView

app_name = 'blogproject'


urlpatterns = [
    url(r'^post/(?P<article_id>[0-9]+)/(?P<url_slug>[-\w]+)/$', views.post_detail, name='post'),
    url(r'^auth/$', views.check_auth, name='auth'),
    url(r'^single-article/(?P<rand_id>[A-Za-z0-9]+)/$', views.single_article),
    url(r'^all-articles/$', views.get_articles_all),
    url(r'^single-article/(?P<rand_id>[A-Za-z0-9]+)/summary$', views.get_article_summary),
    url(r'^archive/$', PostArchiveView.as_view(), name='archive'),
]

commonauth/urls.py
from django.conf.urls import url, include
from django.urls import path
from commonauth import views
from rest_framework import routers
from django.views.decorators.csrf import csrf_exempt

app_name = 'commonauth'


urlpatterns = [
    url(r'^login/$', views.do_login, name='login'),
]

blogproject/views.py
import markdown
import re
import json

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from text_summarization.summary import *
from django.views import View
from django.views.decorators.http import require_http_methods
from markdown.extensions.toc import TocExtension, slugify
from django.contrib.auth.decorators import login_required
from blog.models import SocialAuthUsersocialauth, Userip
from blogproject.models import Post, Category, User, Tag
from django.shortcuts import HttpResponse, render, redirect
from comment.models import Comment
from django.core import serializers as core_serializers
from rest_framework import serializers, viewsets


# Create your views here.

def post_detail_test(request, article_id, url_slug):
    pass


@login_required()
def check_auth(request):
    return HttpResponse("ok")


def get_oauth2_from(name):
    oauth2_from = ''

    if name:
        d_user_id = User.objects.get(username=name).id
        try:
            oauth2login = SocialAuthUsersocialauth.objects.get(user_id=d_user_id)
            oauth2_from = oauth2login.provider
        except Exception as e:
            oauth2_from = 'Django'

    return oauth2_from


def post_detail(request, article_id, url_slug):
    try:
        post = get_object_or_404(Post, id=article_id)
        post.increase_views()
        if post.url_slug != url_slug:
            return render(request, '404.html')
    except Exception as e:
        return render(request, '404.html')
    likes = post.likes
    category_id = post.category.id
    tag_name = post.tags.values('name')
    category = get_object_or_404(Category, id=category_id)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        # 'markdown.extensions.toc',
        TocExtension(slugify=slugify)
    ])
    post.content = md.convert(post.content)
    comments = Comment.objects.filter(post=article_id)
    context = {
        'post': post,
        'category': category,
        'tag': tag_name,
        'likes': likes,
        'toc': md.toc,
        'comments': comments,
        'oauth2_from': get_oauth2_from(request.user.username)

    }
    return render(request, 'blogproject/single.html', context=context)


class PostArchiveView(View):

    def get(self, request):

        try:
            post_list = Post.objects.filter(status='published').order_by("-created_time")
            paginator = Paginator(post_list, 16)  # 分页，每页10条数据
            page = request.GET.get('page')
            try:
                contacts = paginator.page(page)  # contacts为Page对象！
            except PageNotAnInteger:
                # If page is not an integer, deliver first page.
                contacts = paginator.page(1)
            except EmptyPage:
                # If page is out of range (e.g. 9999), deliver last page of results.
                contacts = paginator.page(paginator.num_pages)
            category_name_list = Category.objects.all()
            tag_name_list = Tag.objects.all()
            shanshajia = User.objects.get(username='shanshajia')
            year_month = set()  # 设置集合，无重复元素
            for a in post_list:
                year_month.add((a.timestamp.year, a.timestamp.month))  # 把每篇文章的年、月以元组形式添加到集合中
            counter = {}.fromkeys(year_month, 0)  # 以元组作为key，初始化字典
            for a in post_list:
                counter[(a.timestamp.year, a.timestamp.month)] += 1  # 按年月统计文章数目
            year_month_number = []  # 初始化列表
            for key in counter:
                year_month_number.append([key[0], key[1], counter[key]])  # 把字典转化为（年，月，数目）元组为元素的列表
            year_month_number.sort(reverse=True)  # 排序
            context = {
                'blog_list': post_list,
                'blog_list_views': blog_list_views,
                'blog_list_comments': blog_list_comments,
                'tags': tag_name_list,
                'contacts': contacts,
                'blog_list_greats': blog_list_greats,
                'categorys': category_name_list,
                'blog_list_three': blog_list_news,
                'shanshajia': shanshajia,
                'year_month_number': year_month_number,
                'oauth2_from': oauth2_from
            }
        except Exception as e:
            return render(request, '404.html')

        return render(request, 'blogproject/single.html', context=context)


class PostDetailView(View):

    def get(self, request, article_id, url_slug):

        try:
            post = get_object_or_404(Post, id=article_id)
            if post.url_slug != url_slug:
                return render(request, '404.html')
        except Exception as e:
            return render(request, '404.html')
        category_id = post.category.id
        tag_name = post.tags.values('name')
        category = get_object_or_404(Category, id=category_id)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            # 'markdown.extensions.toc',
            TocExtension(slugify=slugify)
        ])
        post.content = md.convert(post.content)
        context = {
            'post': post,
            'category': category,
            'tag': tag_name,
            'toc': md.toc,
        }
        return render(request, 'blogproject/single.html', context=context)


@require_http_methods(["GET"])
def single_article(request, rand_id):
    # 记录访问ip和每个ip的次数
    if 'HTTP_X_FORWARDED_FOR' in request.META:  # 获取ip
        client_ip = request.META['HTTP_X_FORWARDED_FOR']
        client_ip = client_ip.split(",")[0]  # 所以这里是真实的ip
    else:
        client_ip = request.META['REMOTE_ADDR']  # 这里获得代理ip
    ip_exist = Userip.objects.filter(ip=str(client_ip))
    response = {}
    next_article_title = ""
    prev_article_title = ""
    next_article_id = 0
    prev_article_id = 0
    try:
        article = Post.objects.get(status=1, rand_id=rand_id)
        article_id = article.id
        if ip_exist:
            article.increase_views()
        article = Post.objects.filter(status=1).filter(rand_id=rand_id)
        try:
            prev_article_id = Post.objects.filter(id__lt=article_id, status=1).last().id
            prev_article_title = Post.objects.get(id=prev_article_id).title
        except Exception as e:
            response['msg'] = str(e)
            response['error_num'] = 1
        try:
            next_article_id = Post.objects.filter(id__gt=article_id, status=1).first().id
            next_article_title = Post.objects.get(id=next_article_id).title
        except Exception as e:
            response['msg'] = str(e)
            response['error_num'] = 1
        single_article = get_object_or_404(Post, id=article_id, status=1)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            # 'markdown.extensions.toc',
            TocExtension(slugify=slugify)
        ])
        single_article.content = md.convert(single_article.content)
        n = single_article.content.count('<div class="codehilite">', 0, len(single_article.content))
        for i in range(n):
            single_article.content = re.sub(r'<span></span>',
                                            '&nbsp;&nbsp;<button id="ecodecopy" ref="copy" style="'
                                            'background-color: #909399;border: none;cursor: pointer;'
                                            'color: white;'
                                            'padding: 6px 6px;'
                                            'text-align: center;'
                                            'text-decoration: none;'
                                            'display: inline-block;'
                                            'float:right;'
                                            'font-size: 12px" class="copy_btn" '
                                            'data-clipboard-action="copy" '
                                            'data-clipboard-target="#code{}"'
                                            'onclick="copyText()">复制</button> '
                                            '<div style="clear:both"></div>'
                                            '<div class="codehilite" id="code{}">'.format(i, i), single_article.content,
                                            1)
        single_article.content = single_article.content.replace("/media", "https://www.guanacossj.com/media")
        response['list'] = json.loads(
            core_serializers.serialize("json", article, use_natural_foreign_keys=True, ensure_ascii=False))
        response['msg'] = 'success'
        response['markdown'] = single_article.content
        response['error_num'] = 0
        response['prev_article_title'] = prev_article_title
        response['next_article_title'] = next_article_title
        response['prev_article_id'] = prev_article_id
        response['next_article_id'] = next_article_id
    except Exception as e:
        response['msg'] = str(e)
        response['error_num'] = 1
    return HttpResponse(json.dumps(response, ensure_ascii=False))


@require_http_methods(["GET"])
def get_articles_all(request):
    response = {}
    try:
        articles = Post.objects.filter(status=1).order_by("id")
        response['list'] = json.loads(
            core_serializers.serialize("json", articles, use_natural_foreign_keys=True, ensure_ascii=False))
        response['msg'] = 'success'
        response['error_num'] = 0
    except Exception as e:
        response['msg'] = str(e)
        response['error_num'] = 1
    return HttpResponse(json.dumps(response, ensure_ascii=False))


@require_http_methods(["GET"])
def get_article_summary(request, rand_id):
    response = {}
    try:
        stop_word = []
        with open('text_summarization/stopWordList.txt', 'r') as f:
            for line in f.readlines():

templates/blogproject/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
	<meta name="author" content="Kodinger">
	<title>Sign In For ArithmeticJia</title>
	<link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/my-login.css">
    <link rel="stylesheet" type="text/css" href="http://at.alicdn.com/t/font_1039987_vv3f26czet.css">
    <style type="text/css">
        input {
            outline: none;
        }
        input.form-control:focus {
            border-color: #f5ab35;
            outline: none;
            box-shadow:none;
        }
    </style>
</head>
<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					</br>
                    {% if message %}
                        <div style="text-align: center">
                            <span class="alert alert-warning">{{ message }}</span>
                        </div>
                    {% endif %}
                    </br>
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Login</h4>
							<form method="POST" action="{% url 'commonauth:login' %}">
                                {% csrf_token %}
                                <div style="display: none;">
                                    <input id="next" type="text" name="next_url" value="{{ next_url }}" />
                                </div>
                                <div class="form-group">
									<label for="username">Username</label>

									<input id="username" type='text' class="form-control" name="username" value="" required autofocus>
								</div>

								<div class="form-group">
									<label for="password">Password
										<a href="#" class="float-right" style="color: #f5ab35">
											Forgot Password?
										</a>
									</label>
									<input id="password" type="password" class="form-control" name="password" required data-eye>
								</div>

								<div class="form-group">
									<label>
										<input type="checkbox" name="remember"> Remember Me
									</label>
								</div>

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-info btn-block" style="background: #f5ab35;border-color: #f5ab35">
										Login
									</button>
								</div>
								<div class="margin-top20 text-center">
									Don't have an account? <a href="/blog/register" style="color: #f5ab35">Create One</a>
								</div>
                                <div style="text-align: center;padding: 10px">
                                    <div style="display:inline-block;"><span class="iconfont icon-github">&nbsp;</span><a style="color: black;text-decoration: none;" href="{% url "social:begin" "github" %}">GitHub</a></div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <div style="display:inline-block;"><span class="iconfont icon-weibo">&nbsp;</span><a style="color: black;text-decoration: none;" href="{% url "social:begin" "weibo" %}">Weibo</a></div>&nbsp;&nbsp;&nbsp;
                                </div>
							</form>
						</div>
					</div>
					<div class="footer">
                            Copyright &copy; 2019.Company name All rights reserved.苏ICP备19007197号 <a href="https://www.guanacossj.com" target="_blank" title="arithmeticjia">arithmeticjia</a> - Collect from <a href="https://www.guanacossj.com/" title="arithmeticjia" target="_blank">arithmeticjia</a>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="/static/jquery-2.1.4/jquery.min.js"></script>
	<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
	<script src="/static/js/my-login.js"></script>
</body>
</html>

templates/blogproject/pyexplain.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="/static/images/Jiaicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Online Python Interpreter</title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
      #run {
          width: 20%; /*规定按钮的宽度*/
          margin-top: 10px; /*留出和输入框的间距*/
      }
      #code {
        font-size: 25px;
        resize: none;
      }
      #output {
        font-size: 25px;
        resize: none;
      }
    </style>
  </head>
  <body><!--在下面的注释中 bs 代表 bootstrap -->
  <div class="container"><!-- 页面的整体布局 -->
      <div class="row"> <!-- 这一行单独用来放标题 -->
        <div class="col-lg-12"> <!-- 根据 bs规定，所有内容应放在 col 中。这一列占满一行 -->
          <p class="text-center h1"> <!-- text-center 是 bs 中央排版类，h1 是 bs 一号标题类 -->
            Online Python Interpreter
          </p>
        </div>
      </div>
      <hr><!-- 标题和真正内容的分割线 -->
      <div class="row"><!-- 这一行用来放置主要内容 -->
        <div class="col-lg-6"><!-- 代码输入部分 -->
          <p class="text-center h3">
            Please enter your code
          </p>
          <textarea id="code" placeholder="Your code here." class="form-control"  ></textarea>
          <div class='text-right'><button id="run" type="button" class="btn btn-primary ">run</button></div>
        </div>
        <div class="col-lg-6"><!-- 结果显示部分 -->
        <p class="text-center h3">Result</p>
        <div class="col-lg-12"><textarea id="output" disabled placeholder="Please input your code and click <run> button to excute your python script" class="text-center form-control"></textarea></div>
        </div>
      </div>
  </div>
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script>
      // 动态大小函数
      function changeSize(ele){
        $(ele).css({'height':'auto','overflow-y':'hidden'}).height(ele.scrollHeight)
      }
      // 应用到输入框
      $('#code').each(function(){
          this.oninput = function(){
            changeSize(this)
          }
        });

      function getCode(){
        return $('#code').val()
      }

      function print(data){
        var ele = document.getElementById('output');
        output.value = data['output'];
        changeSize(output)
      }

      $('#run').click(function(){
        $.ajax({
          url:'/JiaBlog/api/', //代码发送的地址
          type:'POST', // 请求类型
          data: {'code':getCode(),csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),},//调用代码获取函数，获得代码文本
          dataType: 'json',  //期望获取的响应类型为 json
          success: print     // 在请求成功之后调用 pprint 函数，将结果打印到输出框
        })
      })
    </script>
  </body>
</html>

templates/blogproject/register.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<title>Register For ArithmeticJia</title>
	<link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/my-login.css">
    <style type="text/css">
        input {
            outline: none;
        }
        input.form-control:focus {
            border-color: #f5ab35;
            outline: none;
            box-shadow:none; 
        }
    </style>
</head>
<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
                    </br>
{#					<div class="brand">#}
{#						<img src="/static/images/logo.jpg">#}
{#					</div>#}
                    {% if message %}
                        <div style="text-align: center">
                            <span class="alert alert-warning">{{ message }}</span>
                        </div>
                    {% endif %}
                    </br>
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Register</h4>
							<form method="POST" action="/blog/register/">
                                {% csrf_token %}
								<div class="form-group">
									<label for="name">Name</label>
									<input id="name" type="text" class="form-control" name="username" required autofocus>
								</div>

								<div class="form-group">
									<label for="email">E-Mail</label>
									<input id="email" type="email" class="form-control" name="email" required>
								</div>

								<div class="form-group">
									<label for="password">Password</label>
									<input id="password1" type="password" class="form-control" name="password1" required data-eye>
								</div>

                                <div class="form-group">
									<label for="password">Confirm Password</label>
									<input id="password2" type="password" class="form-control" name="password2" required data-eye>
								</div>

{#								<div class="form-group">#}
{#									<label>#}
{#										<input type="checkbox" name="aggree" value="1"> I agree to the Terms and Conditions#}
{#									</label>#}
{#								</div>#}

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block" style="background: #f5ab35;border-color: #f5ab35">
										Register
									</button>
								</div>
								<div class="margin-top20 text-center" >
									Already have an account? <a href="/blog/login" style="color: #f5ab35">Login</a>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; 2019.Company name All rights reserved.苏ICP备19007197号 <a href="https://www.guanacossj.com" target="_blank" title="arithmeticjia">arithmeticjia</a> - Collect from <a href="https://www.guanacossj.com/" title="arithmeticjia" target="_blank">arithmeticjia</a>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="/static/jquery-2.1.4/jquery.min.js"></script>
	<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
	<script src="/static/js/my-login.js"></script>
</body>
</html>

templates/blogproject/testsearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <title>Awesome Search Box</title>
    <style>
        body{
   margin: 0;
    padding: 0;
    background: #e84118;
}
.search-box{
    position: absolute;
    top:50%;
    left:50%;
    transform: translate(-50%,-50%);
    background: #2f3640;
    height: 40px;
    border-radius: 40px;
    padding: 10px;
}
.search-box:hover>.search-txt{
    width: 240px;
    padding: 0 6px;
}
.search-box:hover>.search-btn{
   background: white;
}
.search-btn{
    color: #e84118;
    float:right ;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    background: #2f3640;
    display: flex;
    justify-content: center;
    align-items: center;
}
.search-txt{
    border: none;
    background: none;
    outline: none;
    float: left;
    padding: 0;
    color: white;
    font-size: 16px;
    transition: 0.4s;
    line-height: 40px;
    width: 0px;
}
    </style>
</head>
<body>
<div class="search-box">
    <input class="search-txt" type="text" name="" placeholder="Type to search">
    <a class="search-btn" href="#">
        <i class="fas fa-search"></i>
    </a>
</div>
</body>
</html>