blog/urls.py
from django.conf.urls import url, include
from django.urls import path
from blog import views
from rest_framework import routers

app_name = 'blog'

# 定义restful的路由地址
router = routers.DefaultRouter()

# 注册restful的路由地址
router.register(r'getarticleinfo', views.GetArticleInfo)
router.register(r'posts', views.PostViewSet, basename='post')
router.register(r"search", views.PostSearchView, basename="search")

urlpatterns = [
    url('^$', views.index, name='index'),
    url(r'^api/', include(router.urls)),
    path('api/index/', views.IndexPostListAPIView.as_view()),
    # path('api/single/', views.PostViewSet.as_view({'get': 'retrieve'})),
    path('api/auth/', include("rest_framework.urls", namespace="rest_framework")),
    url(r'^search/', views.MySearchView(), name='haystack_search'),
    url(r'^index/$', views.blog_index),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/$', views.blog_info, name='article'),
    url(r'^list/$', views.blog_list),
    url(r'^article/(?P<article_id>[0-9]+)/comment/(?P<cid>.+)', views.comment_view, name='comment'),
    url(r'^contact-us/$', views.contact),
    url(r'^savemessage/$', views.savemessage),
    url(r'^articles/(.+)/$', views.blog_category),
    url(r'^greats/$', views.greats),
    url(r'^admin/$', views.admininndex),
    url(r'^admincharts/$', views.admincharts),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.LogoutView.as_view()),
    url(r'^register/$', views.register_view),
    url(r'^upload_file/$', views.upload_file),
    url(r'^file/$', views.Jiafile),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/editor/$', views.usereditor),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/editor/save/$', views.article_save),
    url(r'^mylist/$', views.mylist),
    url(r'^mylist/(?P<article_status>.+)/$', views.mylist_para),
    url(r'^article/editor/create/$', views.article_create),
    url(r'^article/editor/create/save/$', views.article_create_save),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/editor/delete/', views.article_delete),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/cancelcollect/', views.cancelcollect),
    url(r'^editor/userbrief/$', views.editor_userbrief),
    url(r'^editor/addcategory/$', views.editor_addcategory),
    url(r'^onlineeditor/$', views.pyeditor),
    url(r'^api/$', views.api),
    url(r'^upload_images/(?P<article_id>[0-9]+)/$', views.upload_images),
    url(r'^recruitment/$', views.recruitment),
    url(r'^recruitment/info/$', views.recruitment_info),
    url(r'^recruitment/findme/$', views.findme),
    url(r'^film/', views.movie_list, name="movie"),
    url(r'^deletefile/$', views.deletefile),
    url(r'^ajfileupload/$', views.ajupload_file),
    url(r'^filecheck/$', views.filecheck),
    url(r'^list/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.blog_time),
    url(r'^jiadmin/', views.JiaAdmin.as_view()),
    url(r'^resume/', views.Resume.as_view()),
    url(r'^collect/$', views.collect),
    url(r'^comments/(?P<article_id>[0-9]+)$', views.comments),
    url(r'^rss/$', views.RssFeed(), name='rss'),
    url(r'^searchfile/$', views.search_file),
    url(r'^getallarticle/$', views.get_article_all),
    url(r'^getsinglearticle/(?P<article_id>[0-9]+)/$', views.get_article_single),
    url(r'^single-article/(?P<rand_id>[A-Za-z0-9]+)/$', views.single_article),
    url(r'^getallcategory/$', views.get_categroy_all),
    url(r'^getcategoryarticles/(.+)/$', views.get_article_category),
    url(r'^gettagarticles/(.+)/$', views.get_article_tag),
    url(r'^new/search/$', views.BlogSearch.as_view()),
    url(r'^archive/$', views.BlogPostArchive.as_view()),
    url(r'^new/index/$', views.Index.as_view()),
    url(r'^post/(?P<article_id>[0-9]+)/(?P<slug>[-\w]+)/$', views.BlogPost.as_view()),
    url(r'^upload_file_springboot/$', views.upload_facepic_springboot),
    url(r'^sign_in/$', views.sign_in),
    url(r'^getlovefzytodo/$', views.GetLoveFZYToDoList.as_view()),
    url(r'^getlovefzydown/$', views.GetLoveFZYDownList.as_view()),
    url(r'^postlovefzy/$', views.PostLoveFZYInfo.as_view()),
    url(r'^getlovefzytimeline/$', views.GetLoveFZYTimeline.as_view()),
    url(r'^tags/$', views.show_tags),
    url(r'^api/upload/resumes/$', views.upload_resumes),
    url(r'^api/edit/article/(?P<rand_id>[A-Za-z0-9]+)/$', views.edit_article),
    # url(r'^convert/$', views.convert),
]

oblog/urls.py
from django.conf.urls import url, re_path
from oblog import views
from werobot.contrib.django import make_view
from oblog import newrobot
from oblog import robot
from django.conf import settings

app_name = 'oblog'
urlpatterns = [
    url(r'^search/$', views.search),
    url('^$', views.blog_index, name='index'),
    url(r'^index/$', views.blog_index),
    url(r'^about/$', views.aboutme),
    url(r'^article/(?P<article_id>[0-9]+)/$', views.blog_info),
    # url(r'^weather/$',views.getlocalweather),
    # url(r'love/',views.getlove),
    # url(r'lovepic/',views.getlovepic),
    url(r'^document/', views.getdocument),
    url(r'^robot/', views.weixin),
    url(r'^mymenu/', views.mymenu),
    url(r'^download/$', views.file_down, name='download'),
    url(r'^email/', views.sendemail),
    url(r'^login/', views.login, name='login'),
    url(r'^register/', views.register),
    url(r'^logout/', views.logout),
    url(r'^new/', views.newindex),
    url(r'^monitor/', views.monitor),
    url(r'^savemessage/', views.savemessage),
    url(r'^inputtranslate/', views.inputtranslate),
    url(r'^translate/', views.translate),
    url(r'^videotest/', views.videotest),
    url(r'^film/', views.movie_list, name="movie"),
    url(r'^videoplayer/(?P<film_name>.+)/$', views.videoplayer),
    url(r'^article/(?P<article_id>[0-9]+)/comment', views.comment_view, name='comment'),
    url(r'^time/', views.timeline),
    url(r'^greats/(?P<article_id>[0-9]+)', views.greats),
    url(r'^list/', views.blog_list),
    url(r'^articles/(.+)/$', views.blog_category),

]

oblog/forms.py
from django import forms
from oblog.models import Comment


class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'text']

oblog/views.py
from django.db import models
from django.conf import settings
from alipay import AliPay
from django.db.models import Max
from django.views.decorators.csrf import csrf_exempt
import hashlib
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.shortcuts import render_to_response, redirect, get_object_or_404, render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
import requests
from django.shortcuts import render
from oblog.models import Articles, Message, Tag, Category, Note, BlogUser
# from blog.models import Love
from .forms import CommentForm
from .models import Comment
import time
import os
import json
import requests
from wechat_sdk import WechatBasic
from wechat_sdk.exceptions import ParseError
from wechat_sdk.messages import TextMessage
from django.http.response import HttpResponse, HttpResponseBadRequest
from oblog import talk_machine
from wechatpy import WeChatClient
from django.core.mail import send_mail
from .forms import UserForm
from .forms import RegisterForm
from django.shortcuts import render
from . import models
import psutil
import datetime
import execjs
import urllib
import urllib.request
import urllib.parse
import markdown
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


def index(request):
    return render_to_response('index.html')


def blog_index(request):
    # post = request.get_post(Articles, pk=pk)
    blog_list = Articles.objects.filter(status="有效").order_by("-timestamp")[0:10]  # 获取所有数据
    blog_list_views = Articles.objects.filter(status="有效").order_by('-views')[0:10]  # 点击排行
    blog_list_greats = Articles.objects.filter(status="有效").order_by('-greats')[0:10]  # 猜你喜欢
    blog_list_comments = Articles.objects.filter(status="有效").order_by('-comments')[0:10]  # 博主推荐
    blog_list_comments_top = Articles.objects.filter(status="有效").order_by('-comments')[0:1]  # 博主推荐
    tags = Tag.objects.all()
    count = Articles.objects.filter(status="有效").count()
    maxarticle = Articles.objects.filter(status="有效").order_by('-views')[0:1]
    comment_list = Comment.objects.count()
    note = Note.objects.get(id=str(random.randint(1, Note.objects.count())))
    categorys = Category.objects.all()
    context = {
        'maxview': maxarticle,
        'blog_list': blog_list,
        'blog_list_views': blog_list_views,
        'blog_list_greats': blog_list_greats,
        'blog_list_comments': blog_list_comments,
        'comment_list': comment_list,
        'tags': tags,
        'note': note,
        'count': count,
        'categorys': categorys,
        'blog_list_comments_top': blog_list_comments_top,
    }
    return render(request, 'oblog/index.html', context=context)  # 返回index.html页面


def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键词'
        return render(request, 'oblog/list.html', {'error_msg': error_msg})

    blog_list = Articles.objects.filter(title__icontains=q)
    paginator = Paginator(blog_list, 15)  # 分页，每页10条数据
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)  # contacts为Page对象！
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)

    blog_list_views = Articles.objects.filter(status="有效").order_by('-views')[0:10]
    blog_list_greats = Articles.objects.filter(status="有效").order_by("-greats")[0:10]
    comments = Comment.objects.count()
    tags = Tag.objects.all()
    view = []
    count = Articles.objects.count()
    pagelist = round(count / 5)
    pl = []
    for i in range(pagelist):
        pl.append(i + 1)
    # print((pl))
    # maxid = Articles.objects.all().aggregate(Max('views'))
    # maxid = maxid['id__max']
    for ids in range(1, count + 1):
        article = get_object_or_404(Articles, id=str(ids))
        print(article)
        view.append(article.increase_views())
    maxview = int(view.index(max(view))) + 1
    # maxarticle = Articles.objects.filter(views=maxid['views__max']+1)
    maxarticle = Articles.objects.filter(id=maxview)
    categorys = Category.objects.all()
    context = {
        'maxview': maxarticle,
        'blog_list': blog_list,
        'blog_list_views': blog_list_views,
        'tags': tags,
        'pagelists': pl,
        'contacts': contacts,
        'blog_list_greats': blog_list_greats,
        'comments': comments,
        'error_msg': error_msg,
        'categorys': categorys,
    }
    return render(request, 'oblog/list.html', context=context)


def blog_info(request, article_id):
    blogs = Articles.objects.count()  # 获取所有数据
    thisarticle = get_object_or_404(Articles, id=article_id)
    thisarticle.increase_views()
    greats = thisarticle.greats
    thisarticle.body = markdown.markdown(thisarticle.body,
                                         extensions=[
                                             'markdown.extensions.extra',
                                             'markdown.extensions.codehilite',
                                             'markdown.extensions.toc',
                                         ])
    if int(article_id) == 1:
        leftarticle = '这已经是第一篇啦'
    else:
        leftarticle = get_object_or_404(Articles, id=str(int(article_id) - 1))
    if int(article_id) == int(Articles.objects.last().id):
        rightarticle = '这已经是最后一篇啦'
    else:
        rightarticle = get_object_or_404(Articles, id=str(int(article_id) + 1))
    comment_list = thisarticle.comment_set.all()
    maxarticle = Articles.objects.filter(status="有效").order_by('-views')[0:1]
    blog_list_all = Articles.objects.filter(status="有效").order_by("-views")[0:10]
    blog_list_greats = Articles.objects.filter(status="有效").order_by("-greats")[0:10]
    blog_list_comments = Articles.objects.filter(status="有效").order_by("-comments")[0:10]
    blog_list_comments_top = Articles.objects.filter(status="有效").order_by('-comments')[0:1]  # 博主推荐
    category_id = thisarticle.category.id
    tag_name = thisarticle.tags.values('name')
    tag_name = [item[key] for item in tag_name for key in item]
    tag = (" ".join(tag_name))
    category = get_object_or_404(Category, id=category_id)
    comments = Comment.objects.count()
    note = Note.objects.get(id=str(random.randint(1, Note.objects.count())))
    categorys = Category.objects.all()
    context = {
        'blog_list_all': blog_list_all,
        'maxview': maxarticle,
        'blog_list': thisarticle,
        'comment_list': comment_list,
        'right_blog_list': rightarticle,
        'left_blog_list': leftarticle,
        'category': category,
        'tag': tag_name,
        'tags': tag,
        'greats': greats,
        'blog_list_greats': blog_list_greats,
        'blog_list_comments': blog_list_comments,
        'comments': comments,
        'note': note,
        'categorys': categorys,
        'blog_list_comments_top': blog_list_comments_top,
    }
    return render(request, 'oblog/info.html', context=context)  # 返回info.html页面


def blog_list(request):
    # post = request.get_post(Articles, pk=pk)
    blog_list = Articles.objects.filter(status="有效").order_by("-timestamp")  # 获取所有数据
    blog_list_views = Articles.objects.filter(status="有效").order_by('-views')[0:10]
    blog_list_greats = Articles.objects.filter(status="有效").order_by("-greats")[0:10]
    blog_list_comments = Articles.objects.filter(status="有效").order_by("-comments")[0:10]
    blog_list_comments_top = Articles.objects.filter(status="有效").order_by('-comments')[0:1]  # 博主推荐
    paginator = Paginator(blog_list, 15)  # 分页，每页15条数据
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)  # contacts为Page对象！
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)
    print(blog_list_views)
    tags = Tag.objects.all()
    view = []
    count = Articles.objects.count()
    pagelist = round(count / 3)
    pl = []
    for i in range(pagelist):
        pl.append(i + 1)
    maxarticle = Articles.objects.filter(status="有效").order_by('-views')[0:1]
    comments = Comment.objects.count()
    categorys = Category.objects.all()
    context = {
        'maxview': maxarticle,
        'blog_list': blog_list,
        'blog_list_views': blog_list_views,
        'tags': tags,
        'pagelists': pl,
        'contacts': contacts,
        'blog_list_greats': blog_list_greats,
        'blog_list_comments': blog_list_comments,
        'comments': comments,
        'categorys': categorys,
        'blog_list_comments_top': blog_list_comments_top,
    }
    # print((maxarticle))
    return render(request, 'oblog/list.html', context=context)


def aboutme(request):
    if request.method == 'GET':
        # 取出当前在models表中所有的留言信息 ,返回到前端
        allmessage = Message.objects.all()
        count = Articles.objects.count()
        blog_list_views = Articles.objects.filter(status="有效").order_by('-views')[0:10]  # 点击排行
        blog_list_greats = Articles.objects.filter(status="有效").order_by('-greats')[0:10]  # 猜你喜欢
        blog_list_comments = Articles.objects.filter(status="有效").order_by('-comments')[0:10]  # 博主推荐
        blog_list_comments_top = Articles.objects.filter(status="有效").order_by('-comments')[0:1]
        note = Note.objects.get(id=str(random.randint(1, Note.objects.count())))
        tags = Tag.objects.all()
        view = []
        maxarticle = Articles.objects.filter(status="有效").order_by('-views')[0:1]
        comment_list = Comment.objects.count()
        categorys = Category.objects.all()
        context = {

templates/oblog/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/images/Jiaicon.ico">

    <title>Sign In For ArithmeticJia</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/signin.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/zh_CN/sdk.js#xfbml=1&version=v5.0&appId=2513272488741954&autoLogAppEvents=1"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="http://at.alicdn.com/t/font_1039987_vv3f26czet.css">
  </head>

  <body>
    <script>
        // This is called with the results from from FB.getLoginStatus().
        function statusChangeCallback(response) {
          // The response object is returned with a status field that lets the
          // app know the current login status of the person.
          // Full docs on the response object can be found in the documentation
          // for FB.getLoginStatus().
          if (response.status === 'connected') {
            // Logged into your app and Facebook.
            testAPI();
          } else {
            // The person is not logged into your app or we are unable to tell.
            document.getElementById('status').innerHTML = 'Please log ' +
              'into this app.';
          }
        }

        // This function is called when someone finishes with the Login
        // Button.  See the onlogin handler attached to it in the sample
        // code below.
        function checkLoginState() {
          FB.logout(function(response) {
            // Person is now logged out
          });

          FB.getLoginStatus(function(response) {
            statusChangeCallback(response);
          });
        }

        window.fbAsyncInit = function() {
          FB.init({
            appId      : '2513272488741954',
            cookie     : true,  // enable cookies to allow the server to access
                                // the session
            xfbml      : true,  // parse social plugins on this page
            version    : 'v5.0' // use graph api version 2.8
          });
          FB.AppEvents.logPageView();


          // Now that we've initialized the JavaScript SDK, we call
          // FB.getLoginStatus().  This function gets the state of the
          // person visiting this page and can return one of three states to
          // the callback you provide.  They can be:
          //
          // 1. Logged into your app ('connected')
          // 2. Logged into Facebook, but not your app ('not_authorized')
          // 3. Not logged into Facebook and can't tell if they are logged into
          //    your app or not.
          //
          // These three cases are handled in the callback function.

          FB.getLoginStatus(function(response) {
            statusChangeCallback(response);
          });
        };

        // Load the SDK asynchronously
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "https://connect.facebook.net/en_US/sdk.js";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

        // Here we run a very simple test of the Graph API after login is
        // successful.  See statusChangeCallback() for when this call is made.
        function testAPI() {
          console.log('Welcome!  Fetching your information.... ');
          FB.api('/me', function(response) {
            console.log('Successful login for: ' + response.name);
            document.getElementById('status').innerHTML =
              'Thanks for logging in, ' + response.name + '!';
            window.open.href="https://www.guanacossj.com";  //在同当前窗口中打开窗口
          });
        }
    </script>
    <div class="container">

      <form class="form-signin" method="post" action="{% url 'oblog:login' %}">
          {% if message %}
              <div class="alert alert-warning">{{ message }}</div>
          {% endif %}
          {% csrf_token %}
        <h2 class="form-signin-heading" style="text-align: center">Sign In</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="text" id="inputUsername" name='username' class="form-control" placeholder="Username" required autofocus>
        </br>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
        <div style="display: none;">
            <input id="next" type="text" name="next_url" value="{{ next_url }}" />
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
      <div class="form-signin">
          <button class="btn btn-lg btn-primary btn-block" onclick="window.location.href = '/oblog/register'">Register in</button>
      </div>
        <div style="text-align: center">
            <div style="display:inline-block;"><span class="iconfont icon-github">&nbsp;</span><a style="color: black;text-decoration: none;" href="{% url "social:begin" "github" %}">GitHub</a></div>&nbsp;&nbsp;&nbsp;
            <div style="display:inline-block;"><span class="iconfont icon-weibo">&nbsp;</span><a style="color: black;text-decoration: none;" href="{% url "social:begin" "weibo" %}">Weibo</a></div>&nbsp;&nbsp;&nbsp;
            <div style="display:inline-block;"><span class="iconfont icon-Facebook">&nbsp;</span><a style="color: black;text-decoration: none;" href="{% url "social:begin" "facebook" %}">Facebook</a></div>&nbsp;&nbsp;&nbsp;
            <div style="display:inline-block;"><span class="iconfont icon-google">&nbsp;</span><a style="color: black;text-decoration: none;" href="{% url "social:begin" "google-oauth2" %}">Google</a></div>
{#          <div style="text-align: center"><span class="iconfont icon-github">&nbsp;</span><a style="color: black;text-decoration: none;" href="{% url "social:begin" "facebook" %}">Facebook Login</a></div>#}
        </div>
        </br>
        <div id="fb-root" style="text-align: center">
            <script async defer crossorigin="anonymous" src="https://connect.facebook.net/zh_CN/sdk.js#xfbml=1&version=v5.0&appId=2513272488741954&autoLogAppEvents=1"></script>
            <div class="fb-login-button" data-width="" data-size="medium" data-button-type="continue_with" data-auto-logout-link="true" data-use-continue-as="true" data-onlogin="checkLoginState()"></div>
            <div id="status"></div>
{#            <fb:login-button scope="public_profile,email" onlogin="checkLoginState();"></fb:login-button>#}
        </div>
    </div> <!-- /container -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/oblog/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/images/Jiaicon.ico">

    <title>Register For ArithmeticJia</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/signin.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <form class="form-signin" method="post" action="/JiaBlog/register/">
          {% if message %}
              <div class="alert alert-warning">{{ message }}</div>
          {% endif %}
          {% csrf_token %}
        <h2 class="form-signin-heading" style="text-align: center">Register</h2>
        <label for="inputUsername" class="sr-only">Email address</label>
        <input type="text" id="inputUsername" name='username' class="form-control" placeholder="Username" required autofocus>
        </br>
        <label for="inputPassword" class="sr-only">Password1</label>
        <input type="password" id="inputPassword" name="password1" class="form-control" placeholder="Password" required>
        </br>
        <label for="inputPassword" class="sr-only">Password2</label>
        <input type="password" id="inputPassword" name="password2" class="form-control" placeholder="Password Again" required>
        </br>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="text" id="inputUsername" name='email' class="form-control" placeholder="Email" required autofocus>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/oblog/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <li>{{ translates }}</li>

</head>
<body>

</body>
</html>